schema_version = "1.0.0"

id = "io_scene_fbx_compat"
version = "5.1.0"
name = "FBX format - Compat"
tagline = "FBX addon patched for backwards-compatibility"
maintainer = "Back-compat by: UnDrew, Original add-on by: Blender Foundation"
type = "add-on"

website = "https://github.com/Un-Drew/io_scene_fbx_compat"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export FBX from/to disk"
